In [1]:
!pip install cupy-cuda11x

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 MB 6.4 MB/s eta 0:00:00


In [4]:
USE_GPU = False

if USE_GPU:
    import cupy as xp
else:
    import numpy as xp

# User Input
N = int(input("Enter size of vector/matrix (N): "))

# Input Vectors
print("Enter elements for Vector A:")
A = xp.array([int(input(f"A[{i}]: ")) for i in range(N)])
print("Enter elements for Vector B:")
B = xp.array([int(input(f"B[{i}]: ")) for i in range(N)])

# Vector Addition
C = A + B

print("\nVector A:", A)
print("Vector B:", B)
print("Addition (A + B):", C)

# Input Matrices
print("\nEnter elements for Matrix D:")
D = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        D[i, j] = int(input(f"D[{i}][{j}]: "))

print("Enter elements for Matrix E:")
E = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        E[i, j] = int(input(f"E[{i}][{j}]: "))

# Matrix Multiplication
F = D @ E

print("\nMatrix D:")
print(D)

print("\nMatrix E:")
print(E)

print("\nMultiplication Result (D x E):")
print(F)

Enter size of vector/matrix (N): 5
Enter elements for Vector A:
A[0]: 0
A[1]: 1
A[2]: 2
A[3]: 3
A[4]: 4
Enter elements for Vector B:
B[0]: 0
B[1]: 2
B[2]: 4
B[3]: 6
B[4]: 8

Vector A: [0 1 2 3 4]
Vector B: [0 2 4 6 8]
Addition (A + B): [ 0  3  6  9 12]

Enter elements for Matrix D:
D[0][0]: 0
D[0][1]: 1
D[0][2]: 2
D[0][3]: 3
D[0][4]: 4
D[1][0]: 0
D[1][1]: 2
D[1][2]: 4
D[1][3]: 6
D[1][4]: 8
D[2][0]: 0
D[2][1]: 1
D[2][2]: 2
D[2][3]: 3
D[2][4]: 4
D[3][0]: 0
D[3][1]: 2
D[3][2]: 4
D[3][3]: 6
D[3][4]: 8
D[4][0]: 0
D[4][1]: 1
D[4][2]: 2
D[4][3]: 3
D[4][4]: 4
Enter elements for Matrix E:
E[0][0]: 0
E[0][1]: 2
E[0][2]: 4
E[0][3]: 6
E[0][4]: 8
E[1][0]: 0
E[1][1]: 1
E[1][2]: 2
E[1][3]: 3
E[1][4]: 4
E[2][0]: 0
E[2][1]: 2
E[2][2]: 4
E[2][3]: 6
E[2][4]: 8
E[3][0]: 0
E[3][1]: 1
E[3][2]: 2
E[3][3]: 3
E[3][4]: 4
E[4][0]: 0
E[4][1]: 2
E[4][2]: 4
E[4][3]: 6
E[4][4]: 8

Matrix D:
[[0 1 2 3 4]
 [0 2 4 6 8]
 [0 1 2 3 4]
 [0 2 4 6 8]
 [0 1 2 3 4]]

Matrix E:
[[0 2 4 6 8]
 [0 1 2 3 4]
 [0 2 4 6 8]
 [0 1 2 3 4

In [ ]:
8